#!/bin/bash

text_yellow="$(tput setaf 3 2>/dev/null || echo '\e[0;33m')"  # Yellow
text_reset="$(tput sgr 0 2>/dev/null || echo '\e[0m')"  # text_ Resets

function print_info(){
    printf "${text_yellow}$1${text_reset}\n"
}

function ubuntu_upgrade(){
    print_info "Update..."
    sudo apt update

    print_info "Upgrade..."
    sudo apt upgrade -y
    sudo apt dist-upgrade -y

    print_info "Resolvendo pacotes quebrados..."
    sudo apt -f -y install

    print_info "limpando o repositório local..."
    sudo apt autoremove -y
    sudo apt autoclean -y
    sudo apt clean -y
}

function arch_upgrade(){
    echo "TODO"
}

#######################################################################
# MAIN
#######################################################################
OS=$(grep "^ID=" /etc/os-release | cut -d "=" -f2)

case $OS in
    ubuntu)
        ubuntu_upgrade
        ;;
    arch)
        arch_upgrade
        ;;
    *)
        echo "Unsupported OS"
        echo "values supperteds: 'ubuntu' 'arch'"
        exit 1
        ;;
esac