FROM ubuntu:24.04

ENV DEBIAN_FRONTEND=noninteractive
ENV TERM="tmux-256color"

# Instalação de dependências necessárias
RUN apt update && apt upgrade -y && apt install -y \
    sudo \
    tzdata \
    locales

# This block represent the initial installation of init script (./dotfiles).
# uncomment this block if you want simulate - inside container - that's packages already been installeds
########################################################
RUN apt update && apt upgrade -y && apt install -y \
    git git-extras \
    python3 \
    python3-testresources \
    python3-venv \
    python3-pip \
    python3-watchdog

RUN apt update && apt install -y software-properties-common \
    && apt-add-repository -y ppa:ansible/ansible \
    && apt update \
    && apt install -y ansible
########################################################

RUN rm -rf /var/lib/apt/lists/*

# Gerar e configurar locale
RUN locale-gen en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8

RUN ln -fs /usr/share/zoneinfo/Etc/UTC /etc/localtime \
    && dpkg-reconfigure --frontend noninteractive tzdata

# Configurar sudo para não exigir senha
RUN echo "ALL ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers
RUN echo "ubuntu:ubuntu" | chpasswd

# Definir o usuário para "ubuntu"
WORKDIR /home/ubuntu

COPY . .

RUN chown -R ubuntu:ubuntu /home/ubuntu

USER ubuntu

# Defina o comando padrão
CMD ["tail", "-f", "/dev/null"]